version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'odoo'
      POSTGRES_PASSWORD: 'odoo'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_backups:/backups   # mount for SQL backups
    restart: always

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./custom_addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    restart: always

volumes:
  db_data:
