name: Odoo ECS Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Step 1: Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   # Change your region

    # Step 3: Login to ECR Public
    - name: Login to Amazon ECR Public
      uses: aws-actions/amazon-ecr-login@v2

    # Step 4: Build and push Docker image
    - name: Build Docker image
      run: |
        docker build -t odoo:latest .
        docker tag odoo:latest public.ecr.aws/w8u6m5x9/odoo-ecs:latest
        docker push public.ecr.aws/w8u6m5x9/odoo-ecs:latest

    # Step 5: Update ECS service
    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster odoo-cluster \
          --service odoo-service \
          --force-new-deployment
